name: Pre-commit CI Lite

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: 'style: :rotating_light: auto fix by pre-commit.ci'
